export const CHARACTER_IMAGES = {
    SWIM: [
        './assets/img/1.Sharkie/3.Swim/1.png',
        './assets/img/1.Sharkie/3.Swim/2.png',
        './assets/img/1.Sharkie/3.Swim/3.png',
        './assets/img/1.Sharkie/3.Swim/4.png',
        './assets/img/1.Sharkie/3.Swim/5.png',
        './assets/img/1.Sharkie/3.Swim/6.png',
    ],

    DEAD: [
        './assets/img/1.Sharkie/6.dead/1.Poisoned/1.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/2.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/3.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/4.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/5.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/6.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/7.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/8.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/9.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/10.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/11.png',
        './assets/img/1.Sharkie/6.dead/1.Poisoned/12.png',
    ],

    DEAD_ELECTRO: [
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/1.png',
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/2.png',
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/3.png',
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/4.png',
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/5.png',
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/6.png',
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/7.png',
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/8.png',
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/9.png',
        './assets/img/1.Sharkie/6.dead/2.Electro_shock/10.png',
    ],

    HURT: [
        './assets/img/1.Sharkie/5.Hurt/1.Poisoned/1.png',
        './assets/img/1.Sharkie/5.Hurt/1.Poisoned/2.png',
        './assets/img/1.Sharkie/5.Hurt/1.Poisoned/3.png',
        './assets/img/1.Sharkie/5.Hurt/1.Poisoned/4.png',
        './assets/img/1.Sharkie/5.Hurt/1.Poisoned/5.png',
    ],

    IDLE: [
        './assets/img/1.Sharkie/1.IDLE/1.png',
        './assets/img/1.Sharkie/1.IDLE/2.png',
        './assets/img/1.Sharkie/1.IDLE/3.png',
        './assets/img/1.Sharkie/1.IDLE/4.png',
        './assets/img/1.Sharkie/1.IDLE/5.png',
        './assets/img/1.Sharkie/1.IDLE/6.png',
        './assets/img/1.Sharkie/1.IDLE/7.png',
        './assets/img/1.Sharkie/1.IDLE/8.png',
        './assets/img/1.Sharkie/1.IDLE/9.png',
        './assets/img/1.Sharkie/1.IDLE/10.png',
        './assets/img/1.Sharkie/1.IDLE/11.png',
        './assets/img/1.Sharkie/1.IDLE/12.png',
        './assets/img/1.Sharkie/1.IDLE/13.png',
        './assets/img/1.Sharkie/1.IDLE/14.png',
        './assets/img/1.Sharkie/1.IDLE/15.png',
        './assets/img/1.Sharkie/1.IDLE/16.png',
        './assets/img/1.Sharkie/1.IDLE/17.png',
        './assets/img/1.Sharkie/1.IDLE/18.png',
    ],

    LONG_IDLE: [
        './assets/img/1.Sharkie/2.Long_IDLE/I1.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I2.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I3.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I4.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I5.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I6.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I7.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I8.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I9.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I10.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I11.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I12.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I13.png',
        './assets/img/1.Sharkie/2.Long_IDLE/I14.png',
    ],

    FIN_SLAP_ATTACK: [
        './assets/img/1.Sharkie/4.Attack/Fin_slap/1.png',
        './assets/img/1.Sharkie/4.Attack/Fin_slap/2.png',
        './assets/img/1.Sharkie/4.Attack/Fin_slap/3.png',
        './assets/img/1.Sharkie/4.Attack/Fin_slap/4.png',
        './assets/img/1.Sharkie/4.Attack/Fin_slap/5.png',
        './assets/img/1.Sharkie/4.Attack/Fin_slap/6.png',
        './assets/img/1.Sharkie/4.Attack/Fin_slap/7.png',
        './assets/img/1.Sharkie/4.Attack/Fin_slap/8.png',
    ],

    BUBBLE_FORMATION: [
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/op1_with_bubble_formation/1.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/op1_with_bubble_formation/2.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/op1_with_bubble_formation/3.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/op1_with_bubble_formation/4.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/op1_with_bubble_formation/5.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/op1_with_bubble_formation/6.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/op1_with_bubble_formation/7.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/op1_with_bubble_formation/8.png',
    ],

    POISON_FORMATION: [
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/For_Whale/1.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/For_Whale/2.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/For_Whale/3.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/For_Whale/4.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/For_Whale/5.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/For_Whale/6.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/For_Whale/7.png',
        './assets/img/1.Sharkie/4.Attack/Bubble_trap/For_Whale/8.png',
    ],
};